<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-29 04:30
=======
# Generated by Django 4.2.2 on 2023-06-29 18:48
>>>>>>> 045912c7083ebe1f5fea4aaa96a76a178187f188

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('quantity', models.PositiveSmallIntegerField(default=0)),
=======
                ('quantity', models.PositiveIntegerField(default=0)),
>>>>>>> 045912c7083ebe1f5fea4aaa96a76a178187f188
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
